# Generated by Django 3.2.23 on 2024-01-01 16:06

from django.db import migrations, models
import passthrough.operations


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0002_add_index_on_version_for_content_type_and_db'),
    ]

    operations = [
        passthrough.operations.LockTimeout(
        ),
        migrations.AddField(
            model_name='revision',
            name='using',
            field=models.TextField(blank=True, help_text='The alias of the database used on this revision.', null=True, verbose_name='using'),
        ),
    ]
