# Generated by Django 4.2.15 on 2024-09-01 17:23

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("reversion", "0003_add_cast_index_on_object_id"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
CREATE INDEX CONCURRENTLY IF NOT EXISTS "reversion_version_recover_optimization_id_desc" ON "reversion_version" (content_type_id, db, object_id, id DESC);
            """,
            reverse_sql="""
DROP INDEX CONCURRENTLY IF EXISTS "reversion_version_recover_optimization_id_desc";
""",
            elidable=False,
        ),
    ]
